version: '3.8'
services:
  chadding:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    networks:
      - chadding

  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chadding

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Chadding
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-config/my.cnf:/etc/mysql/my.cnf 
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chadding

volumes:
  mysql-data:

networks:
  chadding:
